name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_DB: bao
          POSTGRES_USER: bao
          POSTGRES_PASSWORD: bao
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://bao:bao@localhost:5432/bao

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'

      - name: Install system dependencies
        run: sudo apt-get install -y libpq-dev

      - name: Install Ruby gems
        run: bundle install --jobs 4 --retry 3

      - name: Install JS packages
        run: yarn install

      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run ESLint
        run: yarn lint

      - name: Run RSpec tests
        run: bundle exec rspec
